import { expect, test } from '@playwright/test'
import { fixedNow, paymentSnapshot } from '../fixtures/oracles'
import { noHorizontalOverflow, noTransferAction, stubApi } from './fixtures'

for (const width of [1280, 390]) {
  test(`expired underpaid receipt, reference copy and later Paid at ${width}px`, async ({ page, context }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    await context.grantPermissions(['clipboard-read', 'clipboard-write'])
    const api = await stubApi(page, 'underpaid')
    const payment = { ...paymentSnapshot('underpaid'), tx_hash: '9d1f4c8a2be7a684d203a78f6b51c904e8f2d76519a0c3be62f41795a8d36c20' }
    api.setPayment(payment)
    await page.clock.pauseAt(new Date(fixedNow + 1000))
    await page.goto('/')
    await page.getByTestId('continue').click()
    await expect(page.getByTestId('transfer-amount')).toHaveText(/43\.69\s*USDT/)
    await expect(page.getByTestId('countdown')).toBeVisible()
    await expect(page.getByTestId('transfer-qr')).toBeVisible()
    await page.clock.fastForward(900000)
    await noTransferAction(page)
    await expect(page.getByTestId('countdown')).toHaveCount(0)
    const status = page.getByTestId('payment-status')
    await expect(status).toHaveAttribute('data-status', 'underpaid')
    await expect(status.getByRole('status').filter({ hasText: /^Payment incomplete$/ })).toHaveText('Payment incomplete')
    await expect(page.locator('.received-summary')).toContainText('120.00 USDT received')
    await expect(page.locator('.received-summary')).not.toContainText('received at')
    await expect(page.locator('.received-summary a')).toHaveAttribute('href', 'https://tronscan.org/transaction/9d1f4c8a2be7a684d203a78f6b51c904e8f2d76519a0c3be62f41795a8d36c20/overview')
    await expect(page.locator('.step.done > .step-marker')).toHaveText(['✓', '✓'])
    await expect(page.locator('.confirmation-step.incomplete > .step-marker')).toHaveText('×')
    await expect(page.getByText("Can't be fixed here", { exact: true })).toBeVisible()
    await expect(page.getByText('Action needed', { exact: true })).toHaveCount(0)
    await expect(page.getByTestId('incomplete-subtitle')).toHaveText('120.00 of 163.69 USDT received · the rate for the rest expired at 08:52')
    await expect(status.locator('.receipt dt')).toHaveText(['Received', 'Still owed', 'Transaction', 'Payment reference'])
    await expect(status.locator('.receipt dd')).toHaveText(['120.00 USDT', '43.69 USDT', '9d1f4c8a2be7…', 'AQH-100306-PMT'])
    await expect(status).not.toContainText(/Send only|refund|safe/)
    const cells = status.locator('.receipt > div')
    const [first, second] = await cells.evaluateAll(nodes => nodes.slice(0, 2).map(node => { const rect = node.getBoundingClientRect(); return { x: rect.x, y: rect.y } }))
    if (width === 1280) { expect(first!.y).toBe(second!.y); expect(second!.x).toBeGreaterThan(first!.x) }
    else { expect(second!.y).toBeGreaterThan(first!.y); expect(first!.x).toBe(second!.x) }
    await noHorizontalOverflow(page)
    await page.screenshot({ path: testInfo.outputPath(`incomplete-${width}.png`), fullPage: true, animations: 'disabled' })
    await status.getByRole('button', { name: 'Copy reference', exact: true }).click()
    await expect(status.getByRole('button', { name: 'Copied', exact: true })).toBeVisible()
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('AQH-100306-PMT')
    await page.clock.runFor(3100)
    await expect(status.getByRole('button', { name: 'Copy reference', exact: true })).toBeVisible()
    expect(api.current()).toEqual(payment)
    api.setPayment({ ...paymentSnapshot('paid'), tx_hash: payment.tx_hash })
    await page.clock.runFor(2200)
    await expect(status).toHaveAttribute('data-status', 'paid')
    await expect(status.getByRole('status').filter({ hasText: /^Paid$/ })).toHaveText('Paid')
    await expect(page.getByTestId('incomplete-subtitle')).toHaveCount(0)
    await noTransferAction(page)
  })
}

test('long reference and transaction stay readable without mobile overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 900 })
  const api = await stubApi(page, 'underpaid')
  api.setPayment({ ...paymentSnapshot('underpaid'), payment_reference: 'AQH-1234567890123456789012345678901234567890123456789012345678901234567890-PMT', tx_hash: '9d1f4c8a2be7a684d203a78f6b51c904e8f2d76519a0c3be62f41795a8d36c20' })
  await page.clock.pauseAt(new Date(fixedNow + 1000))
  await page.goto('/')
  await page.getByTestId('continue').click()
  await expect(page.getByTestId('transfer-qr')).toBeVisible()
  await page.clock.fastForward(900000)
  await expect(page.getByTestId('incomplete-subtitle')).toBeVisible()
  await expect(page.locator('.underpaid-incomplete .receipt dd').last()).toHaveText('AQH-1234567890123456789012345678901234567890123456789012345678901234567890-PMT')
  await noHorizontalOverflow(page)
  const receipt = await page.locator('.underpaid-incomplete .receipt').boundingBox()
  expect(receipt!.x + receipt!.width).toBeLessThanOrEqual(390)
})
